AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles for Cost Optimization Functions

Resources:
  CostOptimizationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EC2CostOptimizationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                  - ec2:DescribeVolumes
                  - ec2:DeleteVolume
                  - ec2:DescribeAddresses
                  - ec2:ReleaseAddress
                Resource: "*"
